### ISSUE TITLE
What is needed for 1.0.0?

### ISSUE THREAD

**Issue by tsloughter** [fishcakez/acceptor_pool#2]
You said you'd open an issue to explain what needs to be done before cutting 1.0.

**Comment by fishcakez** [comment]
- [x] remove `permanent` children (awkward with graceful stop)
- [x] on `accept_socket` transfer control to pool (so that can avoid calling `prim_inet`)
- [x] handle `{0,0,0,0}` listen socket info (should lookup local info on accept in that case)

**Comment by tsloughter** [comment]
I'm looking into these. I definitely can handle removing permanent children support. The second one I'm still trying to understand what needs to be done and prim_inet call it is to avoid...

**Comment by tsloughter** [comment]
And for the last one... I've actually been using `{0,0,0,0}` already, what is missing?

**Comment by fishcakez** [comment]
> The second one I'm still trying to understand what needs to be done and prim_inet call it is to avoid.

There is hack to allow code reload by putting the code for accepting in another module as a tail call, and then calling back to the parent module: https://github.com/fishcakez/acceptor_pool/blob/1cc3f657b6f4d587ad1f26bd79434b9d5247709c/src/acceptor_loop.erl#L45. The code has to abuse internals of `gen_tcp` right now because its possible the `acceptor` trapped exits in the `init` function and the `acceptor_pool` tries to shut it down but it is blocked accepting. If the `acceptor_pool` owns the socket, it can close the socket before running shutdown. This also means we can guarantee to have closed the listen socket before the pool's supervision tree exits.

> And for the last one... I've actually been using {0,0,0,0} already, what is missing?

The pool has some code to display the port information about child processes, if `{0,0,0,0}` is used the child's sockname is shown as `{{0,0,0,0}, Port}` when it should show the actual IP (i.e. if listening on `{0,0,0,0}` we need to call `inet:sockname` after accept).

**Comment by fishcakez** [comment]
@tsloughter not required but if you could switch travis to use rebar3 as well that'd be good.

**Comment by tsloughter** [comment]
@fishcakez so you want to use just gen_tcp:accept instead of the async acceptance?

**Comment by fishcakez** [comment]
@tsloughter yes if the socket ownership is passed to the acceptor pool

**Comment by tsloughter** [comment]
So like this? https://github.com/fishcakez/acceptor_pool/pull/6

**Comment by fishcakez** [comment]
These tasks should be complete so should be ready to release 1.0

**Comment by getong** [comment]
I think so, and please push the 1.0 tag to hex.pm.

**Comment by tsloughter** [comment]
@fishcakez ping

**Comment by getong** [comment]
Wait for #10 to be merged. @fishcakez

**Comment by getong** [comment]
Is there any issue? If no, I think you can make the tag 1.0.0. @fishcakez

**Comment by tsloughter** [comment]
@fishcakez if you add me on hex for the package I can publish 1.0.0.
